version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://db:27017/carbonmate
    depends_on:
      - db
    networks:
      - carbonmate-network

  db:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - carbonmate-network

volumes:
  mongo-data:

networks:
  carbonmate-network:
    driver: bridge