version: '3.8'

services:
  app:
    build:
      context: ./projeto/back-end
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb+srv://Matteo:Matteo@cluster0.qmljj.mongodb.net/nome_do_banco_de_dados?retryWrites=true&w=majority
    networks:
      - carbonmate-network

networks:
  carbonmate-network:
    driver: bridge