version: '3.8'

services:
  app:
    build: 
      context: ./projeto/back-end
      dockerfile: Dockerfile      
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo-carbonmate:27017/carbonmate
    networks:
      - carbonmate-network

networks:
  carbonmate-network:
    driver: bridge